### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by JhonSquare** [Daysquare/BLOG-DAYSQUARE#1]
Por favor encárgate tú del botón de la newsletter de la landing page.
![66302593-bot-n-cuadrado-p-rpura-newsletter](https://user-images.githubusercontent.com/12977365/26926908-d9798228-4c4f-11e7-88fc-81241d4001d2.jpg)

**Comment by delfinbeta** [comment]
Jajaja hola ya va primero explicame qué vas hacer y cómo te colaboro? Para organizarme de tiempo

**Comment by JhonSquare** [comment]
Hola. De momento ando probando la interfaz de github siguiendo el curso de platzi. Por cierto gracias por colaborar conmigo. No tengo nada definido todavía, tan solo tengo la idea de ir creando un blog al que poder aplicarle todas las nuevas tecnologías que voy aprendiendo en Platzi y a su vez ir comentándolas en el propio blog para crear contenido. Pero tan solo es una idea...¿Qué te parece?

**Comment by JhonSquare** [comment]
Voy a cerrar está Issue porque todavía queda mucho para llegar al diseño de botones y demás.
